[package]
name = "xrplt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.xrpl-rust]
git = "https://github.com/sephynox/xrpl-rust.git"
branch = "dev"
